### ISSUE TITLE
[Bug]: TimeFrameUnit issue

### ISSUE THREAD

**Issue by drixie** [alpacahq/alpaca-trade-api-python#522] opened 2021-11-02 06:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The example in the README specifies the ability to use custom time ranges to fetch data. 

However, TimeFrameUnit does not import at the moment

ImportError: cannot import name 'TimeFrameUnit' from 'alpaca_trade_api.rest' 

### Expected Behavior

Fetch OHLCV data in accordance with the timeframe specified

### Steps To Reproduce

```markdown
from alpaca_trade_api.rest import REST, TimeFrame, TimeFrameUnit
```

**Comment by gnvk** [comment] 2021-11-02 07:08
This is because #492 has not yet been released.

**Comment by gnvk** [comment] 2021-11-02 07:54
Please update to https://pypi.org/project/alpaca-trade-api/1.4.1/. If the issue is solved, close it, if not, let us know!

**Comment by drixie** [comment] 2021-11-02 21:47
TimeFrameUnit is covered in the readme of the current stable version. Perhaps the readme should be modified until the feature is released in a stable version 

Could you please help with a resource that shows how to install the dev version. I tried this but it didn't work - pip install  https://pypi.org/project/alpaca-trade-api/1.4.1

**Comment by gnvk** [comment] 2021-11-03 06:29
> TimeFrameUnit is covered in the readme of the current stable version. Perhaps the readme should be modified until the feature is released in a stable version
> 
> Could you please help with a resource that shows how to install the dev version. I tried this but it didn't work - pip install https://pypi.org/project/alpaca-trade-api/1.4.1

It's not a dev version, you can simply install it with
```
pip install alpaca-trade-api==1.4.1
```

**Closed** 2021-11-18 04:07 UTC
