### ISSUE TITLE
Initializing the REST api fails to connect

### ISSUE THREAD

**Issue by sidewaiise** [alpacahq/alpaca-trade-api-python#100] opened 2019-07-31 10:56 UTC
Running a python application inside Docker container.

```
api = tradeapi.REST('<api-key>', '<api-secret>', api_version='v2')
account = api.get_account()
api.list_positions()
```

Also, have environment var `APCA_API_BASE_URL="https://paper-api.alpaca.markets"`

I get this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by ttt733** [comment] 2019-07-31 23:05
This seems like it's more likely to be an issue with your environment than with the SDK. I'm able to use the API in my own environment. Are you sure that the network connection is set up properly for your Docker container?

**Comment by sidewaiise** [comment] 2019-07-31 23:10
Hi Trevor,

Yes, ive added a separate function that uses http.client. Im able to
manually hit the rest api /v2/account and get a valid response with my
token.

Just wondering if theres any additional settings that are defaulted in
thelibrary using urllib3 that i should be aware of and potentially override
for use with my docker setup?

Cheers

**Comment by sidewaiise** [comment] 2019-08-03 05:04
further to this issue... looks like what might be happening, is when I set the BASE_URL, KEY_ID, SECRET_KEY from the environment, you get funny characters getting parsed by the python SDK.

Example: 

```
export APCA_API_BASE_URL="https://paper-api.alpaca.markets"
```

returns as: 

```
https://paper-api.alpaca.markets\r
```

**Comment by ttt733** [comment] 2020-01-29 04:29
Since this isn't something I've been able to reproduce, it seems to me like this might be something strange about the way Docker is being accessed. I'm going to close this, but if anyone else has similar issues feel free to add more information.

**Closed by ttt733** 2020-01-29 04:29 UTC

**Comment by pseudopeach** [comment] 2022-07-25 19:27
I was getting this issue. It was happening intermittently, which was especially weird. Changing to the `api_version` arg instead of the `base_url` are when initializing the API seems to have fixed it for me:

`alpaca = api.REST(secrets['API_KEY'], secrets['API_SECRET'], api_version='v2')`
